services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432" #host port : container port
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    #files will be saved on machine instead of deleting it after container stopped or removed
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5055:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres # Ensure pgAdmin starts only after the PostgreSQL service is up


      # Command: docker compose up -d (-d to always run in the background)
